ui: mocha-bdd
scripts:
  - "bower_components/polyfills/element.js"
  - "dist/med.test.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: 6..latest
  - name: ie
    version: latest
  - name: iphone
    version: 6.1
  - name: ie
    version: 10..latest
